name: Build Desktop
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install Vulkan SDK
        uses: humblepenguinn/setup-vulkan-sdk@v1.2.0
        with:
          vulkan-query-version: 1.3.268.0
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true
      - name: Install dependencies (bun)
        uses: oven-sh/setup-bun@v1
      - name: Install Tauri dependencies
        run: bun install
      - name: Build App
        run: bun run tauri build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VocalWrite-Windows
          path: src-tauri/target/release/bundle/nsis/*.exe
